# Github action that updates the code version tags, adds a changelog and drafts a release when
# a new version tag is added.
name: Stable Gym release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: rickstaa/release-please-action@optional_pyproject_toml
        with:
          release-type: python
          package-name: stable-gym
